// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _12_WebAPI_WithEFCore.Data;

#nullable disable

namespace _12_WebAPI_WithEFCore.Migrations
{
    [DbContext(typeof(CompanyDbContext))]
    [Migration("20250619034727_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("_12_WebAPI_WithEFCore.Data.Department", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Sales Department",
                            Name = "Sales"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Engineering Department",
                            Name = "Engineering"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Quanlity Assurance",
                            Name = "QA"
                        });
                });

            modelBuilder.Entity("_12_WebAPI_WithEFCore.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Salary")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DepartmentId = 2,
                            Name = "John Doe",
                            Position = "Engineer",
                            Salary = 60000.0
                        },
                        new
                        {
                            Id = 2,
                            DepartmentId = 1,
                            Name = "Jane Smith",
                            Position = "Manager",
                            Salary = 75000.0
                        },
                        new
                        {
                            Id = 3,
                            DepartmentId = 3,
                            Name = "Sam Brown",
                            Position = "QA",
                            Salary = 50000.0
                        },
                        new
                        {
                            Id = 4,
                            DepartmentId = 2,
                            Name = "John Doe",
                            Position = "Technician",
                            Salary = 50000.0
                        });
                });

            modelBuilder.Entity("_12_WebAPI_WithEFCore.Models.Employee", b =>
                {
                    b.HasOne("_12_WebAPI_WithEFCore.Data.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("_12_WebAPI_WithEFCore.Data.Department", b =>
                {
                    b.Navigation("Employees");
                });
#pragma warning restore 612, 618
        }
    }
}
